# Generated by Django 2.2 on 2023-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('processed_image', models.ImageField(blank=True, upload_to='processed_images/')),
                ('classified', models.CharField(blank=True, max_length=200)),
                ('e_hr', models.CharField(max_length=30, null=True)),
                ('e_min', models.CharField(max_length=30, null=True)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
