# Generated by Django 2.2 on 2023-03-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
    ]
