# Generated by Django 2.2 on 2023-03-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20230320_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='classified',
            new_name='analyze',
        ),
    ]
