# Generated by Django 2.2 on 2023-03-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20230322_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='analyze',
            new_name='analyzed',
        ),
    ]
