# Generated by Django 2.2 on 2023-03-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20230322_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_time',
            new_name='uploaded',
        ),
    ]
