# Generated by Django 2.2 on 2023-04-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20230322_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='analyzed_info',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
